# Generated by Django 5.1.3 on 2024-12-29 19:00

import quiz_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(upload_to=quiz_app.models.Image.get_upload_to),
        ),
    ]
