# Generated by Django 5.1.3 on 2024-12-29 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz_app", "0002_alter_image_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="quiz_app.question",
            ),
        ),
        migrations.AlterField(
            model_name="image", name="file", field=models.ImageField(upload_to="dummy"),
        ),
    ]
