# Generated by Django 5.1.3 on 2024-12-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz_app", "0003_image_question_alter_image_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
