# Generated by Django 5.1.3 on 2025-02-04 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dragdrop_app", "0001_initial"),
        ("quiz_app", "0006_quizresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="container",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="dragdrop_app.container",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="dragdrop_app.item",
            ),
        ),
    ]
