# Generated by Django 5.1.3 on 2025-02-09 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pixi_app2", "0002_pixiimage_image_pixitask_music"),
        ("quiz_app", "0008_rename_container_image_containerdragdrop_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="taskpixi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="pixi_app2.pixitask",
            ),
        ),
    ]
