# Generated by Django 5.1.3 on 2025-02-14 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz_app", "0010_image_page_background"),
    ]

    operations = [
        migrations.RemoveField(model_name="image", name="page_background",),
    ]
