# Generated by Django 5.1.3 on 2025-02-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz_app", "0014_quiz_unique_id_alter_quiz_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="unique_id",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
