# Generated by Django 5.1.3 on 2025-02-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_alter_payment_stripe_payment_intent_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
