# Generated by Django 5.1.3 on 2025-02-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_alter_payment_stripe_subscription_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                    ("forever", "Forever"),
                ],
                max_length=10,
            ),
        ),
    ]
