# Generated by Django 5.1.3 on 2025-02-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_alter_stripepayment_user_kassapayment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kassapayment",
            old_name="kassa_subscription_id",
            new_name="information_payment",
        ),
    ]
