# Generated by Django 5.1.3 on 2025-02-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payment",
            "0007_rename_kassa_subscription_id_kassapayment_information_payment",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="kassapayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refund", "Refund"),
                    ("refund_failed", "Refund Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
