# Generated by Django 5.1.3 on 2025-02-24 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0008_alter_kassapayment_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="kassapayment", name="refunds",),
    ]
