# Generated by Django 5.1.3 on 2025-01-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="points", field=models.IntegerField(default=0),
        ),
    ]
