# Generated by Django 5.1.3 on 2025-02-04 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dragdrop_app", "0002_alter_container_task_alter_item_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="DragDropType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("classification", "Распределение объектов"),
                            ("sequence-completion", "Продолжение последовательности"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name="dragdroptask", old_name="task", new_name="description",
        ),
        migrations.AddField(
            model_name="dragdroptask",
            name="task_name",
            field=models.CharField(
                choices=[
                    ("resettle", "Рассели"),
                    ("place", "Положи"),
                    ("continue", "Продолжи"),
                    ("fill", "Заполни"),
                    ("replace", "Замени на верные"),
                    ("fill_replace", "Заполни и замени"),
                ],
                default="continue",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="dragdroptask",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="dragdrop_app.dragdroptype",
            ),
        ),
    ]
