# Generated by Django 5.1.3 on 2025-02-07 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dragdrop_app", "0005_dragdropname"),
    ]

    operations = [
        migrations.RemoveField(model_name="dragdroptask", name="type",),
        migrations.AddField(
            model_name="dragdroptask",
            name="name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="dragdrop_app.dragdropname",
            ),
        ),
        migrations.AlterField(
            model_name="dragdroptask",
            name="task_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("resettle", "Рассели"),
                    ("place", "Положи"),
                    ("continue", "Продолжи"),
                    ("fill", "Заполни"),
                    ("replace", "Замени на верные"),
                    ("fill_replace", "Заполни и замени"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
