# Generated by Django 5.1.3 on 2025-02-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dragdrop_app", "0006_remove_dragdroptask_type_dragdroptask_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="dragdroptask", name="task_name",),
    ]
