# Generated by Django 5.1.3 on 2025-02-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dragdrop_app", "0008_dragdroptask_unique_id_alter_dragdroptask_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dragdroptask",
            name="unique_id",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
