# Generated by Django 5.1.3 on 2025-02-09 18:15

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pixi_app2", "0002_pixiimage_image_pixitask_music"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="pixitask", managers=[("tasks", django.db.models.manager.Manager()),],
        ),
    ]
