# Generated by Django 5.1.3 on 2025-02-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pixi_app2", "0003_alter_pixitask_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="pixitask",
            name="animation",
            field=models.CharField(
                choices=[("glow", "Glow"), ("shake", "Shake"), ("scale", "Scale")],
                default="glow",
                max_length=10,
            ),
        ),
    ]
