# Generated by Django 5.1.3 on 2025-02-13 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pixi_app2", "0004_pixitask_animation"),
        ("quiz_app", "0009_image_taskpixi"),
    ]

    operations = [
        migrations.AddField(
            model_name="pixitask",
            name="page_background",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="page_background_images",
                to="quiz_app.image",
            ),
        ),
        migrations.AddField(
            model_name="pixitask",
            name="pixi_background",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pixi_background_images",
                to="quiz_app.image",
            ),
        ),
    ]
