# Generated by Django 5.1.3 on 2025-02-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pixi_app2", "0005_pixitask_page_background_pixitask_pixi_background"),
    ]

    operations = [
        migrations.AddField(
            model_name="pixitask",
            name="unique_id",
            field=models.CharField(
                max_length=10, editable=False, blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="pixitask",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
